# Generated by Django 2.0 on 2018-03-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientNutritionalValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='value')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vegetarian_cookbook.Ingredient', verbose_name='ingredient')),
            ],
            options={
                'verbose_name': 'nutrient',
                'verbose_name_plural': 'nutrients',
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='tag name')),
            ],
            options={
                'verbose_name': 'nutrient',
                'verbose_name_plural': 'nutrients',
            },
        ),
        migrations.AddField(
            model_name='ingredientnutritionalvalue',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetarian_cookbook.Nutrient', verbose_name='nutrient'),
        ),
    ]
