# Generated by Django 2.0 on 2018-03-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0004_auto_20180320_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='carbohydrate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='carbohydrate'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='energy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='energy'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='fat'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='protein'),
        ),
    ]
