# Generated by Django 2.0 on 2018-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0005_auto_20180321_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='counter'),
        ),
    ]
