# Generated by Django 2.0 on 2018-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0008_auto_20180412_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='title'),
        ),
    ]
