# Generated by Django 2.0 on 2018-04-13 17:47

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0009_auto_20180412_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='image'),
        ),
    ]
