# Generated by Django 2.1.7 on 2019-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0011_ingredientnutritionalvalue_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='manually_carbohydrate',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=7, null=True, verbose_name='carbohydrate'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='manually_energy',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=7, null=True, verbose_name='energy'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='manually_fat',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=7, null=True, verbose_name='fat'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='manually_protein',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=7, null=True, verbose_name='protein'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='manually_weight',
            field=models.IntegerField(blank=True, default=None, help_text='Weight after cooking, in grams', null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='unit',
            name='plural',
            field=models.CharField(blank=True, help_text='Example: cups (comma separated if language has more 2 plural forms)', max_length=250, verbose_name='plural form'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='carbohydrate'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='energy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='energy'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='fat'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='protein'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='weight',
            field=models.IntegerField(default=0, help_text='Weight after cooking, in grams', verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='quantity on additional unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(help_text='Example: cup', max_length=250, verbose_name='unit name'),
        ),
    ]
