# Generated by Django 2.0.4 on 2018-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0011_ingredientnutritionalvalue_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='manually_carbohydrate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='carbohydrate'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='manually_energy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='energy'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='manually_fat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='fat'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='manually_protein',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='protein'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='manually_weight',
            field=models.IntegerField(blank=True, default=0, help_text='Weight after cooking, in grams', verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='carbohydrate'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='energy',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='energy'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='fat'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='protein'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='weight',
            field=models.IntegerField(default=0, help_text='Weight after cooking, in grams', verbose_name='weight'),
        ),
    ]
