# Generated by Django 2.0.4 on 2018-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0012_auto_20180529_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='manually_weight',
            field=models.IntegerField(default=0, help_text='Weight after cooking, in grams', verbose_name='weight'),
        ),
    ]
