# Generated by Django 2.0.4 on 2018-05-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0013_auto_20180529_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='manually_carbohydrate',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=7, null=True, verbose_name='carbohydrate'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='manually_energy',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=7, null=True, verbose_name='energy'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='manually_fat',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=7, null=True, verbose_name='fat'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='manually_protein',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=7, null=True, verbose_name='protein'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='manually_weight',
            field=models.IntegerField(blank=True, default=None, help_text='Weight after cooking, in grams', null=True, verbose_name='weight'),
        ),
    ]
