# Generated by Django 2.0.4 on 2018-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0014_auto_20180529_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='quantity on additional unit'),
        ),
    ]
