# Generated by Django 2.0.4 on 2018-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0015_auto_20180605_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='plural',
            field=models.CharField(blank=True, help_text='Example: cups (comma separated if language has more 2 plural forms)', max_length=250, verbose_name='plural form'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(help_text='Example: cup', max_length=250, verbose_name='unit name'),
        ),
    ]
