# Generated by Django 2.0.4 on 2018-06-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetarian_cookbook', '0016_auto_20180607_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='quantity on additional unit'),
        ),
    ]
